import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {HomeComponent} from './home';
import { MainComponent } from './main/main.component';
import {SharedModule} from '../shared/shared.module';

@NgModule({
  imports: [
    CommonModule,
    SharedModule
  ],
  declarations: [
    HomeComponent,
    MainComponent
  ]
})
export class FinCommonModule { }

// this is where any pages that are shared between fin modules will be located
// core is for global services/interceptors, etc
// shared is for shared components/directives/pipes, but these are simple components
// we may have whole pages that are shared, don't want them in shared
// our hierarchy is: store >> core >> routing >> shared >> fin modules (finCommon, etc)
// our app.module will import: browserModule, sharedModule, any fin modules it puts in <router-outlet>
// our fin modules (generated by the cli) will have ng's CommonModule, just need to add sharedModule... done.
