export const pirateShipRoutesNames = {

    N: 'N',
    Y: 'Y',
    NO: 'NO',
    YES: 'YES',
    REOPEN: 'REOPEN',
    COMPLETE: 'COMPLETED',
    AVAILABLE: 'AVAILABLE',
    IN_PROGRESS: 'IN PROGRESS',
    NOT_STARTED: 'NOT STARTED',
    OFFER_NOT_PRESENT: 'OFFER NOT PRESENT',
    OFFER_WORKFLOW_NOT_SETUP: 'OFFER WORKFLOW NOT SETUP'

};

