export const pirateShipRoutesNames = {

    NO: 'N',
    YES: 'Y',
    REOPEN: 'REOPEN',
    COMPLETED: 'COMPLETED',
    IN_PROGRESS: 'IN PROGRESS',
    NOT_STARTED: 'NOT STARTED',
    OFFER_NOT_PRESENT: 'OFFER NOT PRESENT',
    OFFER_WORKFLOW_NOT_SETUP: 'OFFER WORKFLOW NOT SETUP'

};

