
export const filterLevelMap: {prop: string, hierarchyId: number, levelId: number, levelName: string}[] = [
  {prop: 'productLevel',	hierarchyId: 1, levelId:	1, levelName: 'TG'},
  {prop: 'productLevel',	hierarchyId: 1, levelId:	2, levelName: 'BU'},
  {prop: 'productLevel',	hierarchyId: 1, levelId:	3, levelName: 'PF'},
  {prop: 'productLevel',	hierarchyId: 1, levelId:	4, levelName: 'PID'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	1, levelName: 'LEVEL1'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	2, levelName: 'LEVEL2'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	3, levelName: 'LEVEL3'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	4, levelName: 'LEVEL4'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	5, levelName: 'LEVEL5'},
  {prop: 'salesLevel',	hierarchyId: 2, levelId:	6, levelName: 'LEVEL6'},
  {prop: 'scmsLevel',	hierarchyId: 7, levelId:	1, levelName: 'SCMS'},
  {prop: 'entityLevel',	hierarchyId: 3, levelId:	1, levelName: 'BE'},
  {prop: 'internalBELevel',	hierarchyId: 8, levelId:	1, levelName: 'INTERNAL BE'},
  {prop: 'internalBELevel',	hierarchyId: 8, levelId:	2, levelName: 'INTERNAL SUB BE'},
  {prop: 'glSegLevel',	hierarchyId: 9, levelId:	1, levelName: 'ACCOUNT'},
  {prop: 'glSegLevel',	hierarchyId: 9, levelId:	1, levelName: 'SUB ACCOUNT'},
  {prop: 'glSegLevel',	hierarchyId: 9, levelId:	1, levelName: 'COMPANY'},
];
