export const Submeasure = {
  activeStatus: 'A',
  approvedOnce: 'Y',
  categoryType: 'HW',
  createdBy: 'jodoe',
  createdDate: '2018-12-01T00:11:48.440Z',
  desc: '2 Tier Adjustment',
  endFiscalMonth: '204012',
  id: '5cd5c201b2db8208c0cb4c2f',
  indicators: {
    _id: '5cebd281b79fb724fc8e327d',
    allocationRequired: 'N',
    corpRevenue: 'Y',
    deptAcct: 'N',
    dollarUploadFlag: 'Y',
    dualGaap: 'N',
    groupFlag: 'N',
    manualMapping: 'N',
    passThrough: 'N',
    retainedEarnings: 'N',
    service: 'N',
    transition: 'N',
    twoTier: 'N'
  },
  inputFilterLevel: {
    productLevel: '',
    entityLevel: 'BE',
    glSegLevel: [],
    internalBELevel: 'INTERNAL BE',
    salesLevel: 'LEVEL1',
    scmsLevel: 'SCMS'
  },
  manualMapping: {
    productLevel: '',
    entityLevel: '',
    glSegLevel: [],
    internalBELevel: '',
    salesLevel: '',
    scmsLevel: ''
  },
  groupingSubmeasureId: 6,
  sourceSystemAdjTypeId: 6,
  measureId: 1,
  moduleId: 1,
  manualMixHw: 50,
  manualMixSw: 50,
  inputProductFamily: 'input product family',
  allocProductFamily: 'alloc product family',
  name: '2 Tier Adjustment',
  pnlnodeGrouping: 'Indirect Adjustments',
  processingTime: 'Monthly',
  reportingLevels: [null, 'Indirect Revenue Adjustments', null],
  rules: ['2TSUBDIR-MTD', 'SHIPREV-QTD'],
  sourceId: 4,
  startFiscalMonth: '201905',
  status: 'A',
  submeasureId: 1,
  submeasureKey: 1,
  updatedBy: 'jodoe',
  updatedDate: '2018-12-01T00:11:48.450Z'
};
